/* Generated By:JJTree: Do not edit this line. ASTepDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.google.code.p.relaxws.parser;

public
class ASTepDecl extends SimpleNode {
	
	public ASTepDecl(int id) {
		super(id);
	}

	public ASTepDecl(RelaxWizParser p, int id) {
		super(p, id);
	}
	
	static Object params [][]={
		{
			"type",                 //name of the value
			"^(soap)$",             //validator for the values/ for now only soap supported
			Boolean.FALSE,          //multivalue
			Boolean.TRUE,           //unique. used only if multivalue is true
			"soap"
		},
		{
			"address",              //name of the value
			".*",                   //validator for the values/ for now only soap supported
			Boolean.FALSE,          //multivalue
			Boolean.TRUE,           //unique. used only if multivalue is true
			null
		},
		{
			"interface",            //name of the value
			".*",                   //validator for the values
			Boolean.TRUE,           //multivalue
			Boolean.TRUE,           //unique. used only if multivalue is true
			null                    //null means no def value
		}
	};
	
	private String name=null;
	private MVMap opt = new MVMap("endpoint options", params);
	
	
	public void setName(Object s){
		name=text(s);
	}
	public String getName(){
		return name;
	}
	//returns endpoint options
	public MVMap opt(){
		return opt;
	}
	

}
/* JavaCC - OriginalChecksum=c5e057a570ea8267a4665421091953fc (do not edit this line) */
