/* Generated By:JJTree: Do not edit this line. ASTinDecl.java */

package com.google.code.p.relaxws.parser;

import com.google.code.p.relaxws.parser.SimpleNode;
import com.google.code.p.relaxws.parser.RelaxWizParser;

public class ASTinDecl extends SimpleNode {

    private String name;
    
  public ASTinDecl(int id) {
    super(id);
  }

  public ASTinDecl(RelaxWizParser p, int id) {
    super(p, id);
  }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
