/* Generated By:JJTree: Do not edit this line. ASTnsDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.google.code.p.relaxws.parser;

public
class ASTnsDecl extends SimpleNode {
  public ASTnsDecl(int id) {
    super(id);
  }

  public ASTnsDecl(RelaxWizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=61a4de77e471c6aa04e837460021d7e7 (do not edit this line) */
