/* Generated By:JJTree: Do not edit this line. ASToutDecl.java */

package com.google.code.p.relaxws.parser;

import com.google.code.p.relaxws.parser.SimpleNode;
import com.google.code.p.relaxws.parser.RelaxWizParser;

public class ASToutDecl extends SimpleNode {
    private String name;

  public ASToutDecl(int id) {
    super(id);
  }

  public ASToutDecl(RelaxWizParser p, int id) {
    super(p, id);
  }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    

}
