/* Generated By:JJTree: Do not edit this line. ASToptDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.google.code.p.relaxws.parser;

public
class ASToptDecl extends SimpleNode {
  public ASToptDecl(int id) {
    super(id);
  }

  public ASToptDecl(RelaxWizParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=58532ea5b3482a777f7baf55672027b2 (do not edit this line) */
