/* Generated By:JJTree: Do not edit this line. ASTschemaDecl.java */

package com.google.code.p.relaxws.parser;

import com.google.code.p.relaxws.parser.SimpleNode;
import com.google.code.p.relaxws.parser.RelaxWizParser;

public class ASTschemaDecl extends SimpleNode {
  public ASTschemaDecl(int id) {
    super(id);
  }

  public ASTschemaDecl(RelaxWizParser p, int id) {
    super(p, id);
  }

}
