/* Generated By:JJTree: Do not edit this line. ASTservice.java */

package com.google.code.p.relaxws.parser;

import com.google.code.p.relaxws.parser.SimpleNode;
import com.google.code.p.relaxws.parser.RelaxWizParser;

import java.util.LinkedHashMap;

public class ASTservice extends SimpleNode {

    private String name;
    private String namespace;
    private String documentation=null;
    
    private LinkedHashMap<String,String> nsMap = new LinkedHashMap();

    public ASTservice(int id) {
        super(id);
    }

    public ASTservice(RelaxWizParser p, int id) {
        super(p, id);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
        if(this.documentation==null)documentation=""+name+" service";
    }

    //returns default namespace
    public String getNamespace() {
        return namespace;
    }

    //set default namespace
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    public void setNamespace(String prefix,String uri) {
    	String old=nsMap.get(prefix);
    	if(old!=null && !old.equals(uri))throw new RuntimeException("prefix: `"+prefix+"` already used for namespace: `"+old+"`. new value: `"+uri+"`");
    	nsMap.put(prefix,uri);
    }

    public LinkedHashMap getNamespaces() {
        return nsMap;
    }

    public String getDocumentation() {
        return documentation;
    }

    public void setDocumentation(String documentation) {
    	if(documentation.length()>0)this.documentation = documentation;
    }
}
