/* Generated By:JJTree&JavaCC: Do not edit this line. RelaxWizParserConstants.java */
package com.google.code.p.relaxws.parser;

public interface RelaxWizParserConstants {

  int EOF = 0;
  int NAMESPACE = 6;
  int SERVICE = 7;
  int PORT = 8;
  int OPERATION = 9;
  int IN = 10;
  int OUT = 11;
  int FAULT = 12;
  int TYPES = 13;
  int LBRACE = 14;
  int RBRACE = 15;
  int IDENTIFIER = 16;
  int LETTER = 17;
  int DIGIT = 18;
  int SYMBOL = 19;
  int TRAILING_COMMENT = 20;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"namespace\"",
    "\"service\"",
    "\"port\"",
    "\"operation\"",
    "\"in\"",
    "\"out\"",
    "\"fault\"",
    "\"types\"",
    "\"{\"",
    "\"}\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SYMBOL>",
    "<TRAILING_COMMENT>",
  };

}
