/* Generated By:JJTree&JavaCC: Do not edit this line. RelaxWizParserConstants.java */
package com.google.code.p.relaxws.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RelaxWizParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAMESPACE = 6;
  /** RegularExpression Id. */
  int SET = 7;
  /** RegularExpression Id. */
  int SERVICE = 8;
  /** RegularExpression Id. */
  int PORT = 9;
  /** RegularExpression Id. */
  int OPERATION = 10;
  /** RegularExpression Id. */
  int IN = 11;
  /** RegularExpression Id. */
  int OUT = 12;
  /** RegularExpression Id. */
  int FAULT = 13;
  /** RegularExpression Id. */
  int TYPES = 14;
  /** RegularExpression Id. */
  int LBRACE = 15;
  /** RegularExpression Id. */
  int RBRACE = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int SYMBOL = 20;
  /** RegularExpression Id. */
  int TRAILING_COMMENT = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"namespace\"",
    "\"set\"",
    "\"service\"",
    "\"port\"",
    "\"operation\"",
    "\"in\"",
    "\"out\"",
    "\"fault\"",
    "\"types\"",
    "\"{\"",
    "\"}\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SYMBOL>",
    "<TRAILING_COMMENT>",
    "\"=\"",
    "\"\\\"\"",
  };

}
