/* Generated By:JavaCC: Do not edit this line. RelaxWizParserTreeConstants.java Version 5.0 */
package com.google.code.p.relaxws.parser;

public interface RelaxWizParserTreeConstants
{
  public int JJTSERVICE = 0;
  public int JJTNSDECL = 1;
  public int JJTTYPESDECL = 2;
  public int JJTSCHEMADECL = 3;
  public int JJTRNC = 4;
  public int JJTPORTDECL = 5;
  public int JJTOPERATIONDECL = 6;
  public int JJTMESSAGEDEF = 7;


  public String[] jjtNodeName = {
    "service",
    "nsDecl",
    "typesDecl",
    "schemaDecl",
    "rnc",
    "portDecl",
    "operationDecl",
    "MessageDef",
  };
}
/* JavaCC - OriginalChecksum=08e38d8b9c1e787a0267446ee7efc130 (do not edit this line) */
