/* Generated By:JavaCC: Do not edit this line. RelaxWizParserTreeConstants.java Version 5.0 */
package com.google.code.p.relaxws.parser;

public interface RelaxWizParserTreeConstants
{
  public int JJTSERVICE = 0;
  public int JJTOPTDECL = 1;
  public int JJTNSDECL = 2;
  public int JJTTYPESDECL = 3;
  public int JJTSCHEMADECL = 4;
  public int JJTRNC = 5;
  public int JJTPORTDECL = 6;
  public int JJTOPERATIONDECL = 7;
  public int JJTMESSAGEDEF = 8;


  public String[] jjtNodeName = {
    "service",
    "optDecl",
    "nsDecl",
    "typesDecl",
    "schemaDecl",
    "rnc",
    "portDecl",
    "operationDecl",
    "MessageDef",
  };
}
/* JavaCC - OriginalChecksum=49e4f6e307aec99c692145351774f6b0 (do not edit this line) */
