/* Generated By:JavaCC: Do not edit this line. RelaxWizParserTreeConstants.java Version 5.0 */
package com.google.code.p.relaxws.parser;

public interface RelaxWizParserTreeConstants
{
  public int JJTSERVICE = 0;
  public int JJTOPTDECL = 1;
  public int JJTNSDECL = 2;
  public int JJTEPDECL = 3;
  public int JJTTYPESDECL = 4;
  public int JJTSCHEMADECL = 5;
  public int JJTRNC = 6;
  public int JJTPORTDECL = 7;
  public int JJTOPERATIONDECL = 8;
  public int JJTMESSAGEDEF = 9;


  public String[] jjtNodeName = {
    "service",
    "optDecl",
    "nsDecl",
    "epDecl",
    "typesDecl",
    "schemaDecl",
    "rnc",
    "portDecl",
    "operationDecl",
    "MessageDef",
  };
}
/* JavaCC - OriginalChecksum=f4e5246703ed14a1e0359c7b9e4cd55c (do not edit this line) */
