/* Generated By:JJTree: Do not edit this line. ASTfaultDecl.java */

package com.google.code.p.relaxws.parser;

import com.google.code.p.relaxws.parser.SimpleNode;
import com.google.code.p.relaxws.parser.RelaxWizParser;

public class ASTfaultDecl extends SimpleNode {

    private String name;

  public ASTfaultDecl(int id) {
    super(id);
  }

  public ASTfaultDecl(RelaxWizParser p, int id) {
    super(p, id);
  }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    

}
