/* Generated By:JJTree: Do not edit this line. ASTrnc.java */

package com.google.code.p.relaxws.parser;

import com.google.code.p.relaxws.parser.SimpleNode;
import com.google.code.p.relaxws.parser.RelaxWizParser;

public class ASTrnc extends SimpleNode {

    private String rnc;

  public ASTrnc(int id) {
    super(id);
  }

  public ASTrnc(RelaxWizParser p, int id) {
    super(p, id);
  }

    public String getRnc() {
        return rnc;
    }

    public void setRnc(String rnc) {
        this.rnc = rnc;
    }


    public String toString() {
        String s = super.toString();
        s += " ['" + rnc + "']";
        return s;
    }
}
