/* Generated By:JJTree: Do not edit this line. ASTservice.java */

package com.google.code.p.relaxws.parser;

import com.google.code.p.relaxws.parser.SimpleNode;
import com.google.code.p.relaxws.parser.RelaxWizParser;

public class ASTservice extends SimpleNode {

    private String name;
    private String namespace;
    private String documentation=null;

    public ASTservice(int id) {
        super(id);
    }

    public ASTservice(RelaxWizParser p, int id) {
        super(p, id);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
        if(this.documentation==null)documentation=""+name+" service";
    }

    public String getNamespace() {
        return namespace;
    }

    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    public String getDocumentation() {
        return documentation;
    }

    public void setDocumentation(String documentation) {
    	if(documentation.length()>0)this.documentation = documentation;
    }
}
